-- 預約表 (bookings) 補齊缺失的欄位
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS base_price INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS discount_amount INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS final_price INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deposit_paid INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS platform_fee INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS coach_payout INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS grade TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS attendees_count INTEGER DEFAULT 1;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS learning_status TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS coupon_id TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS coupon_discount INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS series_id TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS recurrence_pattern TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS session_number INTEGER;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS duration_minutes INTEGER DEFAULT 60;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS payment_expires_at TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS plan_id TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS plan_title TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS plan_snapshot TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS settlement_id UUID;

UPDATE bookings
SET duration_minutes = 60
WHERE duration_minutes IS NULL;

-- 重新載入 schema cache
NOTIFY pgrst, 'reload schema';
